export enum MarketingCampaignActionType {
  DISCOUNT = 'DISCOUNT',
  CASHBACK_BOOST = 'CASHBACK_BOOST',
  GIFT_POINTS = 'GIFT_POINTS',
  PROMOCODE_ISSUE = 'PROMOCODE_ISSUE',
  TIER_UPGRADE = 'TIER_UPGRADE',
}
