//SERVER
export const SERVER_ERROR = 574;
//USER
export const USER_PASSWORD_CONFIRM_EXCEPTION_CODE = 1001;
export const USER_REGISTER_EXCEPTION_CODE = 1002;
export const USER_REGISTER_WORKER_EXCEPTION_CODE = 1003;
export const USER_RESET_PASSWORD_EXCEPTION_CODE = 1005;
export const USER_GET_CONTACT_EXCEPTION_CODE = 1006;
export const USER_UPDATE_ROLE_EXCEPTION_CODE = 1007;
export const USER_AUTHORIZATION_EXCEPTION_CODE = 1008;

//DEVICE
export const DEVICE_CREATE_EXCEPTION_CODE = 2001;
export const DEVICE_CREATE_TYPE_EXCEPTION_CODE = 2002;
export const DEVICE_UPDATE_TYPE_EXCEPTION_CODE = 2003;
export const DEVICE_GET_BY_ID_EXCEPTION_CODE = 2004;
export const DEVICE_PROGRAM_TYPE_GET_BY_ID_EXCEPTION_CODE = 2005;
//INCIDENT
export const INCIDENT_CREATE_EXCEPTION_CODE = 3001;
export const INCIDENT_UPDATE_EXCEPTION_CODE = 3002;
export const INCIDENT_GET_ALL_BY_FILTER_EXCEPTION_CODE = 3003;
//ORGANIZATION
export const ORGANIZATION_ADD_WORKER_EXCEPTION_CODE = 4001;
export const ORGANIZATION_VERIFICATE_EXCEPTION_CODE = 4002;
export const ORGANIZATION_UPDATE_EXCEPTION_CODE = 4003;
export const ORGANIZATION_GET_ONE_BY_ID_EXCEPTION_CODE = 4004;
export const ORGANIZATION_CREATE_EXCEPTION_CODE = 4005;
//POS
export const POS_CREATE_EXCEPTION_CODE = 5001;
export const POS_GET_BY_ID_EXCEPTION_CODE = 5002;
export const POS_CONNECTION_PROGRAM_EXCEPTION_CODE = 5003;
export const POS_PATCH_PROGRAM_RATE_EXCEPTION_CODE = 5004;
export const POS_CONNECTION_WORKER_EXCEPTION_CODE = 5005;
//TECH_TASK
export const TECH_TASK_CREATE_EXCEPTION_CODE = 6001;
export const TECH_TASK_UPDATE_EXCEPTION_CODE = 6002;
export const TECH_TASK_GET_SHAPE_EXCEPTION_CODE = 6003;
export const TECH_TASK_COMPLETION_SHAPE_EXCEPTION_CODE = 6004;
export const TECH_TASK_CREATE_TAG_EXCEPTION_CODE = 6005;
export const TECH_TASK_DELETE_EXCEPTION_CODE = 6006;
//WAREHOUSE
export const WAREHOUSE_CREATE_EXCEPTION_CODE = 7001;
export const WAREHOUSE_CREATE_NOMENCLATURE_EXCEPTION_CODE = 7002;
export const WAREHOUSE_UPDATE_NOMENCLATURE_EXCEPTION_CODE = 7003;
export const WAREHOUSE_CREATE_NOMENCLATURE_FILE_EXCEPTION_CODE = 7004;
export const WAREHOUSE_CREATE_CATEGORY_EXCEPTION_CODE = 7005;
export const WAREHOUSE_GET_ALL_NOMENCLATURE_BY_ORG_EXCEPTION_CODE = 7006;
export const WAREHOUSE_GET_ALL_BY_POS_EXCEPTION_CODE = 7007;
export const WAREHOUSE_GET_ONE_BY_ID_EXCEPTION_CODE = 7008;
export const WAREHOUSE_GET_ALL_INVENTORY_ITEM_EXCEPTION_CODE = 7009;
export const WAREHOUSE_SAVE_DOCUMENT_EXCEPTION_CODE = 7010;
export const WAREHOUSE_REMAINING_ITEM_EXCEPTION_CODE = 7011;
export const WAREHOUSE_DELETE_NOMENCLATURE_EXCEPTION_CODE = 7012;
export const SALE_DOCUMENT_CREATE_EXCEPTION_CODE = 7013;
export const WAREHOUSE_EXIST_SUPPLIER_EXCEPTION_CODE = 7014;
export const WAREHOUSE_DELETE_DOCUMENT_EXCEPTION_CODE = 7015;
export const SALE_PRICE_DELETE_EXCEPTION_CODE = 7016;
export const SALE_DOCUMENT_GET_EXCEPTION_CODE = 7017;

//FINANCE
export const FINANCE_CREATE_EXCEPTION_CODE = 8001;
export const FINANCE_RECALCULATE_EXCEPTION_CODE = 8002;
export const FINANCE_RETURN_EXCEPTION_CODE = 8003;
export const FINANCE_GET_ONE_EXCEPTION_CODE = 8004;
//REPORT
export const REPORT_GET_ONE_EXCEPTION_CODE = 9001;
//LOYALTY
export const LOYALTY_CREATE_TAG_EXCEPTION_CODE = 1101;
export const LOYALTY_DELETE_TAG_EXCEPTION_CODE = 1102;
export const LOYALTY_CREATE_CLIENT_EXCEPTION_CODE = 1103;
export const LOYALTY_UPDATE_TAG_EXCEPTION_CODE = 1104;
export const LOYALTY_GET_ONE_EXCEPTION_CODE = 1105;
export const LOYALTY_DEBITING_BALANCE_EXCEPTION_CODE = 1106;
//HR
export const HR_GET_ONE_POSITION_EXCEPTION_CODE = 1201;
export const HR_CREATE_WORKER_EXCEPTION_CODE = 1202;
export const HR_GET_ONE_WORKER_EXCEPTION_CODE = 1203;
export const HR_UPDATE_WORKER_EXCEPTION_CODE = 1204;
export const HR_CREATE_PREPAYMENT_EXCEPTION_CODE = 1205;
export const HR_CREATE_POSITION_EXCEPTION_CODE = 1206;
export const HR_CREATE_PAYMENT_EXCEPTION_CODE = 1207;
//NOTIFICATION
export const NOTIFICATION_CREATE_TEG_EXCEPTION_CODE = 1301;
export const NOTIFICATION_DELETE_TEG_EXCEPTION_CODE = 1302;
export const NOTIFICATION_UPDATE_TEG_EXCEPTION_CODE = 1303;
export const NOTIFICATION_AUTH_EXCEPTION_CODE = 1304;
//MANAGER PAPER
export const MANAGER_PAPER_UPDATE_EXCEPTION_CODE = 1401;
export const MANAGER_PAPER_DELETE_EXCEPTION_CODE = 1402;
export const MANAGER_PAPER_CREATE_EXCEPTION_CODE = 1403;
export const MANAGER_PAPER_PERIOD_ALREADY_SENT_EXCEPTION_CODE = 1404;
export const MANAGER_REPORT_PERIOD_GET_DETAIL_EXCEPTION_CODE = 1405;
export const MANAGER_PAPER_TYPE_UPDATE_EXCEPTION_CODE = 1406;
export const MANAGER_REPORT_PERIOD_DELETE_EXCEPTION_CODE = 1407;

//PERMISSIONS
export const PERMISSION_DENIED_EXCEPTION_CODE = 1501;
