export const Devices = [
  {
    id: 428,
    name: 'Пост 1',
    carWashDeviceMetaData: 'carWashDeviceMetaData',
    status: 'ACTIVE',
    ipAddress: 'ipAddress',
    carWashDeviceTypeId: 1,
    carWashPosId: 66,
  },
  {
    id: 429,
    name: 'Пост 2',
    carWashDeviceMetaData: 'carWashDeviceMetaData',
    status: 'ACTIVE',
    ipAddress: 'ipAddress',
    carWashDeviceTypeId: 1,
    carWashPosId: 66,
  },
  {
    id: 430,
    name: 'Пост 3',
    carWashDeviceMetaData: 'carWashDeviceMetaData',
    status: 'ACTIVE',
    ipAddress: 'ipAddress',
    carWashDeviceTypeId: 1,
    carWashPosId: 66,
  },
  {
    id: 431,
    name: 'Пост 4',
    carWashDeviceMetaData: 'carWashDeviceMetaData',
    status: 'ACTIVE',
    ipAddress: 'ipAddress',
    carWashDeviceTypeId: 1,
    carWashPosId: 66,
  },
  {
    id: 432,
    name: 'Пост 5',
    carWashDeviceMetaData: 'carWashDeviceMetaData',
    status: 'ACTIVE',
    ipAddress: 'ipAddress',
    carWashDeviceTypeId: 1,
    carWashPosId: 66,
  },
  {
    id: 433,
    name: 'Пылесос 1',
    carWashDeviceMetaData: 'carWashDeviceMetaData',
    status: 'ACTIVE',
    ipAddress: 'ipAddress',
    carWashDeviceTypeId: 2,
    carWashPosId: 66,
  },
  {
    id: 1093,
    name: 'Пылесос 3',
    carWashDeviceMetaData: 'carWashDeviceMetaData',
    status: 'ACTIVE',
    ipAddress: 'ipAddress',
    carWashDeviceTypeId: 2,
    carWashPosId: 66,
  },
  {
    id: 2037,
    name: 'Пылесос 3_new',
    carWashDeviceMetaData: 'carWashDeviceMetaData',
    status: 'ACTIVE',
    ipAddress: 'ipAddress',
    carWashDeviceTypeId: 2,
    carWashPosId: 66,
  },
];
