import { IncidentInfoType } from '@prisma/client';

const generateIncidentNames = (count: number) => ({
  connect: Array.from({ length: count }, (_, i) => ({ id: i + 1 })),
});

export const IncidentInfos = [
  // Причины поломки (type: IncidentInfoType.Reason)
  {
    id: 1,
    name: 'Течь',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 2,
    name: 'Регламентные работы',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 3,
    name: 'Травит(пропускает)',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 4,
    name: 'Разрыв',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 5,
    name: 'Нет питания',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 6,
    name: 'Не принимает деньги',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 7,
    name: 'Не держит',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 8,
    name: 'Лопнул',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 9,
    name: 'Износ',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 10,
    name: 'Засор',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 11,
    name: 'Завис',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 12,
    name: 'Залит',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 13,
    name: 'Заклинил',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 14,
    name: 'Вышел из строя',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 15,
    name: 'Переделка',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 16,
    name: 'Полная яма ила',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 17,
    name: 'Сгорел электромотор',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 18,
    name: 'отключение электроснабжения',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 19,
    name: 'Замерз',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 20,
    name: 'Ошибка',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 21,
    name: 'Протечки воздуха',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 22,
    name: 'перезагрузка',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 23,
    name: 'коррозия',
    type: IncidentInfoType.Reason,
    incidentName: generateIncidentNames(181),
  },

  // Предпринятые меры (type: IncidentInfoType.Solution)
  {
    id: 24,
    name: 'замена',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 25,
    name: 'ремонт',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 26,
    name: 'переуплотнил',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 27,
    name: 'Закрыл временно АМС',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 28,
    name: 'Переборка',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 29,
    name: 'Временно отключил функцию',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 30,
    name: 'прочее(пиши примечание)',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 31,
    name: 'Чистка ЭМ-клапана',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 32,
    name: 'замена масла',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 33,
    name: 'Чистка инжектора',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 34,
    name: 'настройка',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 35,
    name: 'промывка',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 36,
    name: 'замер',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 37,
    name: 'разборка/сборка',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 38,
    name: 'чистка',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 39,
    name: 'продувка',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 40,
    name: 'перезапуск',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 41,
    name: 'Сдал в ремонт',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 42,
    name: 'Закрыл временно Пост',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 43,
    name: 'откачка',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 44,
    name: 'Обновление ПО',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 45,
    name: 'переустановка ПО',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 46,
    name: 'Отогрев',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
  {
    id: 47,
    name: 'Снятие-установка',
    type: IncidentInfoType.Solution,
    incidentName: generateIncidentNames(181),
  },
];
