import { IncidentInfoType } from '@prisma/client';

export const IncidentInfos = [
  // Причины поломки (type: IncidentInfoType.Reason)
  { id: 1, name: 'Течь', type: IncidentInfoType.Reason },
  { id: 2, name: 'Регламентные работы', type: IncidentInfoType.Reason },
  { id: 3, name: 'Травит(пропускает)', type: IncidentInfoType.Reason },
  { id: 4, name: 'Разрыв', type: IncidentInfoType.Reason },
  { id: 5, name: 'Нет питания', type: IncidentInfoType.Reason },
  { id: 6, name: 'Не принимает деньги', type: IncidentInfoType.Reason },
  { id: 7, name: 'Не держит', type: IncidentInfoType.Reason },
  { id: 8, name: 'Лопнул', type: IncidentInfoType.Reason },
  { id: 9, name: 'Износ', type: IncidentInfoType.Reason },
  { id: 10, name: 'Засор', type: IncidentInfoType.Reason },
  { id: 11, name: 'Завис', type: IncidentInfoType.Reason },
  { id: 12, name: 'Залит', type: IncidentInfoType.Reason },
  { id: 13, name: 'Заклинил', type: IncidentInfoType.Reason },
  { id: 14, name: 'Вышел из строя', type: IncidentInfoType.Reason },
  { id: 15, name: 'Переделка', type: IncidentInfoType.Reason },
  { id: 16, name: 'Полная яма ила', type: IncidentInfoType.Reason },
  { id: 17, name: 'Сгорел электромотор', type: IncidentInfoType.Reason },
  {
    id: 18,
    name: 'отключение электроснабжения',
    type: IncidentInfoType.Reason,
  },
  { id: 19, name: 'Замерз', type: IncidentInfoType.Reason },
  { id: 20, name: 'Ошибка', type: IncidentInfoType.Reason },
  { id: 21, name: 'Протечки воздуха', type: IncidentInfoType.Reason },
  { id: 22, name: 'перезагрузка', type: IncidentInfoType.Reason },
  { id: 23, name: 'коррозия', type: IncidentInfoType.Reason },

  // Предпринятые меры (type: IncidentInfoType.Solution)
  { id: 24, name: 'замена', type: IncidentInfoType.Solution },
  { id: 25, name: 'ремонт', type: IncidentInfoType.Solution },
  { id: 26, name: 'переуплотнил', type: IncidentInfoType.Solution },
  { id: 27, name: 'Закрыл временно АМС', type: IncidentInfoType.Solution },
  { id: 28, name: 'Переборка', type: IncidentInfoType.Solution },
  { id: 29, name: 'Временно отключил функцию', type: IncidentInfoType.Solution },
  { id: 30, name: 'прочее(пиши примечание)', type: IncidentInfoType.Solution },
  { id: 31, name: 'Чистка ЭМ-клапана', type: IncidentInfoType.Solution },
  { id: 32, name: 'замена масла', type: IncidentInfoType.Solution },
  { id: 33, name: 'Чистка инжектора', type: IncidentInfoType.Solution },
  { id: 34, name: 'настройка', type: IncidentInfoType.Solution },
  { id: 35, name: 'промывка', type: IncidentInfoType.Solution },
  { id: 36, name: 'замер', type: IncidentInfoType.Solution },
  { id: 37, name: 'разборка/сборка', type: IncidentInfoType.Solution },
  { id: 38, name: 'чистка', type: IncidentInfoType.Solution },
  { id: 39, name: 'продувка', type: IncidentInfoType.Solution },
  { id: 40, name: 'перезапуск', type: IncidentInfoType.Solution },
  { id: 41, name: 'Сдал в ремонт', type: IncidentInfoType.Solution },
  { id: 42, name: 'Закрыл временно Пост', type: IncidentInfoType.Solution },
  { id: 43, name: 'откачка', type: IncidentInfoType.Solution },
  { id: 44, name: 'Обновление ПО', type: IncidentInfoType.Solution },
  { id: 45, name: 'переустановка ПО', type: IncidentInfoType.Solution },
  { id: 46, name: 'Отогрев', type: IncidentInfoType.Solution },
  { id: 47, name: 'Снятие-установка', type: IncidentInfoType.Solution },
];
