export const ProgramTypes = [
  {
    id: 1,
    code: 'SOAP',
    name: 'Вода + шампунь',
    carWashDeviceTypeId: 1,
    orderNum: 3,
  },
  {
    id: 2,
    code: 'TIRE',
    name: 'Мойка дисков',
    carWashDeviceTypeId: 1,
    orderNum: 1,
  },
  {
    id: 3,
    code: 'PRESOAK',
    name: 'Активная химия',
    carWashDeviceTypeId: 1,
    orderNum: 2,
  },
  {
    id: 4,
    code: 'BRUSH',
    name: 'Щетка + пена',
    carWashDeviceTypeId: 1,
    orderNum: 4,
  },
  {
    id: 5,
    code: 'WATER',
    name: 'Ополаскивание',
    carWashDeviceTypeId: 1,
    orderNum: 5,
  },
  {
    id: 6,
    code: 'WAX',
    name: 'Воск + защита',
    carWashDeviceTypeId: 1,
    orderNum: 6,
  },
  {
    id: 7,
    code: 'OSMOS',
    name: 'Ополаскивание без разводов',
    carWashDeviceTypeId: 1,
    orderNum: 7,
  },
  {
    id: 8,
    code: 'COMBO1',
    name: 'Комбинация 1',
    carWashDeviceTypeId: 5,
  },
  {
    id: 9,
    code: 'COMBO2',
    name: 'Комбинация 2',
    carWashDeviceTypeId: 5,
  },
  {
    id: 10,
    code: 'TPOWER',
    name: 'T-Power',
    carWashDeviceTypeId: 1,
    orderNum: 8,
  },
  {
    id: 11,
    name: 'Горячая вода',
    carWashDeviceTypeId: 1,
  },
  {
    id: 12,
    name: 'Обезжирка',
    carWashDeviceTypeId: 1,
  },
  {
    id: 13,
    code: 'COMBO3',
    name: 'Комбинация 3',
    carWashDeviceTypeId: 5,
  },
  {
    id: 14,
    code: 'COMBO4',
    name: 'Комбинация 4',
    carWashDeviceTypeId: 5,
  },
  {
    id: 15,
    code: 'DOPFUNC1',
    name: 'Доп. функция 1',
    carWashDeviceTypeId: 5,
  },
  {
    id: 16,
    code: 'DOPFUNC1',
    name: 'Доп. функция 2',
    carWashDeviceTypeId: 5,
  },
  {
    id: 17,
    code: 'DOPFUNC1',
    name: 'Доп. функция 3',
    carWashDeviceTypeId: 5,
  },
  {
    id: 18,
    name: 'Экспресс',
    carWashDeviceTypeId: 5,
    description: 'Для заправок Flash',
  },
  {
    id: 19,
    name: 'Стандарт',
    carWashDeviceTypeId: 5,
    description: 'Для заправок Flash',
  },
  {
    id: 20,
    name: 'Премиум',
    carWashDeviceTypeId: 5,
    description: 'Для заправок Flash',
  },
  {
    id: 21,
    name: 'Пылесос',
    carWashDeviceTypeId: 2,
    description: 'Для регистрации пылесоса.',
  },
  {
    id: 22,
    name: 'Воздух',
    carWashDeviceTypeId: 1,
  },
  {
    id: 23,
    name: 'Летняя',
    carWashDeviceTypeId: 5,
  },
];
