import {
  GroupTechTaskItemTemplate,
  TypeTechTaskItemTemplate,
} from '@prisma/client';

export const TechTaskItemTemplate = [
  {
    id: 1,
    title: 'Засыпано соли, кг',
    code: 'SALT',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 2,
    title: 'Уровень "вода+шампунь", литров',
    code: 'SOAP_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 3,
    title: 'Залив В+Ш',
    code: 'SOAP_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 4,
    title: 'Уровень "активная химия", литров',
    code: 'PRESOAK_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 5,
    title: 'Залив АХ',
    code: 'PRESOAK_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 6,
    title: 'Уровень "мойка дисков", литров',
    code: 'TIRE_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 7,
    title: 'Залив "мойка дисков"',
    code: 'TIRE_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 8,
    title: 'Уровень воск+защита, литр',
    code: 'WAX_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 9,
    title: 'Залив В+З',
    code: 'WAX_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 10,
    title: 'T-POWER уровень, литр',
    code: 'TPOWER_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 11,
    title: 'T-POWER залив',
    code: 'TPOWER_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 12,
    title: 'Уровень щётка+пена',
    code: 'BRUSH_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 13,
    title: 'Залив Щ+П',
    code: 'BRUSH_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 14,
    title: 'Остаток реагента, кг',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Check,
  },
  {
    id: 15,
    title: 'Проверка очистных, норма',
    type: TypeTechTaskItemTemplate.SelectList,
    group: GroupTechTaskItemTemplate.Check,
  },
  {
    id: 16,
    title: 'Километраж',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Check,
  },
  {
    id: 17,
    title: 'Маршрут',
    type: TypeTechTaskItemTemplate.Text,
    group: GroupTechTaskItemTemplate.Check,
  },
  {
    id: 18,
    title: 'Электропотребление, кВТ',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.PowerConsumption,
  },
  {
    id: 19,
    title: 'Насос повышения давления, bar',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Installations,
  },
  {
    id: 20,
    title: 'Установка восстановления давления, psi',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Installations,
  },
  {
    id: 21,
    title: 'Счетчик моточасов',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Installations,
  },
  {
    id: 22,
    title: 'Компрессор, норма',
    type: TypeTechTaskItemTemplate.SelectList,
    group: GroupTechTaskItemTemplate.Installations,
  },
  {
    id: 23,
    title: 'Замена масла компрессора, да/нет',
    type: TypeTechTaskItemTemplate.SelectList,
    group: GroupTechTaskItemTemplate.Installations,
  },
  {
    id: 24,
    title: 'Проверка работоспособности солевого бака, норма',
    type: TypeTechTaskItemTemplate.SelectList,
    group: GroupTechTaskItemTemplate.Softener,
  },
  {
    id: 25,
    title: 'Жесткость воды',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Softener,
  },
  {
    id: 26,
    title: 'Проверка работоспособности и целостности, норма',
    type: TypeTechTaskItemTemplate.SelectList,
    group: GroupTechTaskItemTemplate.Softener,
  },
  {
    id: 27,
    title: 'Счетчик А',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Softener,
  },
  {
    id: 28,
    title: 'Счетчик В',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Softener,
  },
  {
    id: 29,
    title: 'Давление на входе',
    type: TypeTechTaskItemTemplate.SelectList,
    group: GroupTechTaskItemTemplate.Osmosis,
  },
  {
    id: 30,
    title: 'Давление мембраны, psi',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Osmosis,
  },
  {
    id: 31,
    title: 'Расходомер concentrate (Rejeсt water), л/мин',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Osmosis,
  },
  {
    id: 32,
    title: 'Скорость product (Spot Free), л/мин',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Osmosis,
  },
  {
    id: 33,
    title: 'Минерализация - Дименирализованная вода',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Osmosis,
  },
  {
    id: 34,
    title: 'Минерализация - Вода на входе',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Osmosis,
  },
  {
    id: 35,
    title: 'Хлорсодержание',
    type: TypeTechTaskItemTemplate.SelectList,
    group: GroupTechTaskItemTemplate.CarbonFilter,
  },
  {
    id: 36,
    title: 'Проверка работоспособности и целостности',
    type: TypeTechTaskItemTemplate.SelectList,
    group: GroupTechTaskItemTemplate.CarbonFilter,
  },
  {
    id: 37,
    title: 'Остаток соли, кг',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 38,
    title: 'Остаток "вода+шампунь", литров',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 39,
    title: 'Остаток АХ',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 40,
    title: 'Остаток МД',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 41,
    title: 'Остаток ЩП',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 42,
    title: 'Остаток ВЗ',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 43,
    title: 'Остаток T-POWER',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 44,
    title: 'Центральный счетчик',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 45,
    title: 'Осмос product (Spot Free)',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 46,
    title: 'Осмос Concentrate',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 47,
    title: 'Горячая вода',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 48,
    title: 'Weep',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 49,
    title: 'Городской',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 50,
    title: 'Химия',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 51,
    title: 'Уровень ДТ ёмкость 1',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 52,
    title: 'Уровень ДТ ёмкость 2',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 53,
    title: 'Счетчик тепловой энергии',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 54,
    title: 'Счетчик газа',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 55,
    title: 'Заправка ДТ',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 56,
    title: 'Счетчик дизеля подача',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
  {
    id: 57,
    title: 'Уровень ила в центральном илоотстойнике,%',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Counters,
  },
];
