import {
  GroupTechTaskItemTemplate,
  TypeTechTaskItemTemplate,
} from '@prisma/client';

export const TechTaskItemTemplate = [
  {
    id: 1,
    title: 'Засыпано соли, кг',
    code: 'SALT',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 2,
    title: 'Уровень "вода+шампунь", литров',
    code: 'SOAP_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 3,
    title: 'Залив В+Ш',
    code: 'SOAP_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 4,
    title: 'Уровень "активная химия", литров',
    code: 'PRESOAK_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 5,
    title: 'Залив АХ',
    code: 'PRESOAK_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 6,
    title: 'Уровень "мойка дисков", литров',
    code: 'TIRE_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 7,
    title: 'Залив "мойка дисков"',
    code: 'TIRE_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 8,
    title: 'Уровень воск+защита, литр',
    code: 'WAX_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 9,
    title: 'Залив В+З',
    code: 'WAX_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 10,
    title: 'T-POWER уровень, литр',
    code: 'TPOWER_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 11,
    title: 'T-POWER залив',
    code: 'TPOWER_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 12,
    title: 'Уровень щётка+пена',
    code: 'BRUSH_LEVEL',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 13,
    title: 'Залив Щ+П',
    code: 'BRUSH_ADD',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Chemistry,
  },
  {
    id: 14,
    title: 'Остаток реагента, кг',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Check,
  },
  {
    id: 15,
    title: 'Проверка очистных, норма',
    type: TypeTechTaskItemTemplate.SelectList,
    group: GroupTechTaskItemTemplate.Check,
  },
  {
    id: 16,
    title: 'Километраж',
    type: TypeTechTaskItemTemplate.Number,
    group: GroupTechTaskItemTemplate.Check,
  },
  {
    id: 17,
    title: 'Маршрут',
    type: TypeTechTaskItemTemplate.Text,
    group: GroupTechTaskItemTemplate.Check,
  },
];
