export const Warehouses = [
  {
    id: 1,
    name: 'Склад 36 M-01',
    location: 'ул. 9 Января, 68лит3/2',
    managerId: 4,
    posId: 1,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 2,
    name: 'Склад 36 M-02',
    location: 'ул. Солнечная, 8а, корпус 2',
    managerId: 4,
    posId: 2,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 3,
    name: 'Склад 36 М-03',
    location: 'ул. Димитрова, 91а',
    managerId: 4,
    posId: 3,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 4,
    name: 'Склад 36 М-09',
    location: 'Воронежское шоссе',
    managerId: 4,
    posId: 13,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 5,
    name: 'Склад 36 М-13',
    location: 'ул. Новосибирская, 69а',
    managerId: 4,
    posId: 15,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 6,
    name: 'Склад 36 М-12',
    location: 'ул. Димитрова, 159б/2',
    managerId: 4,
    posId: 18,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 7,
    name: 'Склад 36 М-11',
    location: 'ул. Новосибирская, 13',
    managerId: 4,
    posId: 19,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 8,
    name: 'Склад 68 М-01',
    location: 'ул. Агапкина, 2б',
    managerId: 4,
    posId: 27,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 9,
    name: 'Склад 58 М-01',
    location: 'ул.Ладожская 122а',
    managerId: 4,
    posId: 33,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 10,
    name: 'Склад 36 М-25',
    location: 'ул. Острогожская, 111',
    managerId: 4,
    posId: 43,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 11,
    name: 'Склад 36 М-14',
    location: 'ул. Дорожная, 84д',
    managerId: 4,
    posId: 46,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 12,
    name: 'Склад 78 МО-01',
    location: 'Долгоозерная, д. 26.',
    managerId: 4,
    posId: 50,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 13,
    name: 'Склад 77 М-07',
    location: 'квартал Клязьма, 1г',
    managerId: 4,
    posId: 52,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 14,
    name: 'Склад 68 М-02',
    location: 'ул. Московская, 15б',
    managerId: 4,
    posId: 55,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 15,
    name: 'Склад 36 М-15',
    location: 'Брусилова 4е',
    managerId: 4,
    posId: 66,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 16,
    name: 'Склад 36 М-17',
    location: 'ул. Острогожская, 148/4',
    managerId: 4,
    posId: 67,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 17,
    name: 'Склад 58 М-02',
    location: 'пр-т Строителей 2Г',
    managerId: 4,
    posId: 71,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 18,
    name: 'Склад 36 М-20',
    location: 'ул. Шишкова, 140Буч3',
    managerId: 4,
    posId: 78,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 19,
    name: 'Склад 78 МО-02',
    location: 'Ленинградское шоссе, 11',
    managerId: 4,
    posId: 84,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 20,
    name: 'Склад 36 М-18',
    location: 'ул. Солнечная',
    managerId: 4,
    posId: 88,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 21,
    name: 'Склад 36 М-19',
    location: 'ул. Димитрова, 91а',
    managerId: 4,
    posId: 103,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 22,
    name: 'Склад 37 Ф-01',
    location: 'ул. Ивановская, 7а',
    managerId: 4,
    posId: 108,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 23,
    name: 'Склад 92 М-01',
    location: 'Фиолентовское шоссе, 1',
    managerId: 4,
    posId: 118,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 24,
    name: 'Склад 36 М-31',
    location: 'ул. Транспортная, 20а',
    managerId: 4,
    posId: 124,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 25,
    name: 'Склад 36 М-10',
    location: 'ул. Софьи Перовской, 1',
    managerId: 4,
    posId: 127,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 26,
    name: 'Склад 77 М-06',
    location: 'ул. Степана Степанова, 33',
    managerId: 4,
    posId: 131,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 27,
    name: 'Склад 77 М-08',
    location: 'ул. Чернышевского, 64',
    managerId: 4,
    posId: 140,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 28,
    name: 'Склад DS4S-015',
    location: 'микрорайон Павлино, с46',
    managerId: 4,
    posId: 141,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 29,
    name: 'Склад 77 М-05',
    location: 'Белокаменное шоссе, вл. 2а',
    managerId: 4,
    posId: 143,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 30,
    name: 'Склад 36 М-04',
    location: 'ул. Антонова-Овсеенко, 17в',
    managerId: 4,
    posId: 153,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 31,
    name: 'Склад 78 МО-03',
    location: 'Пушкинский район, посёлок Тярлево, Фильтровское шоссе, 1',
    managerId: 4,
    posId: 156,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 32,
    name: 'Склад DS4Pr-71',
    location: 'ул.Ладожская 105',
    managerId: 4,
    posId: 162,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 33,
    name: 'Склад 68 М-03',
    location: 'ул. Комиссара Московского д. 21',
    managerId: 4,
    posId: 164,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 34,
    name: 'Склад DS3-102',
    location: 'Павловск',
    managerId: 4,
    posId: 177,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 35,
    name: 'Склад DS3-105',
    location: 'просп. Бориса Куликова, 42',
    managerId: 4,
    posId: 182,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 36,
    name: 'Склад 36 М-26',
    location: 'ул. Брусилова, 4/1',
    managerId: 4,
    posId: 189,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 37,
    name: 'Склад DS3-112_DS3-124',
    location: 'ул.Дорожная 3п',
    managerId: 4,
    posId: 190,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 38,
    name: 'Склад DS3-113',
    location: 'ул. Бекешская, д.15',
    managerId: 4,
    posId: 191,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 39,
    name: 'Склад 77 М-09',
    location: 'ул. Академика Скрябина, 21',
    managerId: 4,
    posId: 195,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 40,
    name: 'Склад 77 М-12',
    location: 'ул. Красная сосна, 2, к1 стр 10',
    managerId: 4,
    posId: 199,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 41,
    name: 'Склад 36 М-26 Робот',
    location: 'ул. Брусилова, 4/1',
    managerId: 4,
    posId: 208,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 42,
    name: 'Склад DS5-007',
    location: 'ул. Острогожская, 166 е',
    managerId: 4,
    posId: 214,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 43,
    name: 'Склад 77 М-11',
    location: 'п.г.т. Белоозерский, ул. Коммунальная, 12',
    managerId: 4,
    posId: 224,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 44,
    name: 'Склад 36 М-10 Робот',
    location: 'ул. Софьи Перовской, 1',
    managerId: 4,
    posId: 228,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 45,
    name: 'Склад 36 М-28',
    location: 'ул. Кольцовская, 24б',
    managerId: 4,
    posId: 233,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 46,
    name: 'Склад 36 М-30',
    location: 'пр-т Патриотов, 67г',
    managerId: 4,
    posId: 235,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 47,
    name: 'Склад 36 М-36',
    location: 'Набережная Максима Горького 33в',
    managerId: 4,
    posId: 261,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 48,
    name: 'Склад 36 М-30 Робот',
    location: 'пр-т Патриотов, 67г',
    managerId: 4,
    posId: 274,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 49,
    name: 'Склад 36 М-28 Робот',
    location: 'ул. Кольцовская, 24б',
    managerId: 4,
    posId: 275,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 50,
    name: 'Склад DS4St-136',
    location: '-',
    managerId: 4,
    posId: 282,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 51,
    name: 'Склад 68 М-07',
    location: 'ул. Придорожная, д.46',
    managerId: 4,
    posId: 290,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 52,
    name: 'Склад 36 М-15 Робот',
    location: 'Брусилова 4е',
    managerId: 4,
    posId: 295,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 53,
    name: 'Склад 36 М-35 Робот',
    location: 'п. Отрадное, ул. Магистральная 8',
    managerId: 4,
    posId: 308,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 54,
    name: 'Склад 36 М-34',
    location: 'Ветряк, Выборская 17',
    managerId: 4,
    posId: 315,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 55,
    name: 'Склад 36 М-35',
    location: 'п. Отрадное, ул. Магистральная 8',
    managerId: 4,
    posId: 319,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 56,
    name: 'Склад DS_025 Робот',
    location: 'ул. Героев Сибиряков 2б',
    managerId: 4,
    posId: 322,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 57,
    name: 'Склад DS4St-147',
    location: 'Нивский проспект 17, АЗС 161',
    managerId: 4,
    posId: 330,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 58,
    name: 'Склад Автошина М-29 Робот',
    location: 'Острогожская улица, 148/2',
    managerId: 4,
    posId: 331,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 59,
    name: 'Склад 77 М-14',
    location: 'село Михалёво, Загородная улица, 31А',
    managerId: 4,
    posId: 335,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 60,
    name: 'Склад 68 М-04',
    location: 'СХПК "Кузьминский", 68Н-073',
    managerId: 4,
    posId: 337,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 61,
    name: 'Склад 68 М-05',
    location: 'микрорайон "Слобода", улица Мичуринская, д. 224',
    managerId: 4,
    posId: 338,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 62,
    name: 'Склад 68 М-05 Робот',
    location: 'микрорайон "Слобода", улица Мичуринская, д. 224',
    managerId: 4,
    posId: 342,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 63,
    name: 'Склад 36 М-39',
    location: 'ул. Острогожская улица, 148/4',
    managerId: 4,
    posId: 347,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 64,
    name: 'Склад 68 М-06',
    location: 'Московская 13',
    managerId: 4,
    posId: 354,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 65,
    name: 'Склад 77 М-15 Робот',
    location: 'Вокзальная улица, 5/К',
    managerId: 4,
    posId: 364,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: 66,
    name: 'Склад 77 М-15',
    location: 'Вокзальная улица, 5/К',
    managerId: 4,
    posId: 365,
    createdById: 4,
    updateById: 4,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
];
