-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('CREATED', 'PAYMENT_PROCESSING', 'WAITING_PAYMENT', 'PAYMENT_AUTHORIZED', 'PAYED', 'FAILED', 'COMPLETED', 'CANCELED', 'REFUNDED');

-- AlterTable
ALTER TABLE "LTYEquaring" ADD COLUMN     "paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'CREATED';
