//AUTH
export const USER_UNAUTHORIZED_ERROR_CODE = 7;
export const INVALID_OTP_AUTHENTIFICATION_ERROR_CODE = 5;
export const INVALID_REFRESH_AUTHENTIFICATION_ERROR_CODE = 51;
export const INVALID_ACCESS_AUTHENTIFICATION_ERROR_CODE = 52;

//OTP
export const OTP_INTERNAL_SERVER_ERROR_CODE = 6;

//CLIENT
export const CLIENT_EXISTS_CLIENT_EXCEPTION_CODE = 41;
export const CLIENT_NOT_FOUND_EXCEPTION_CODE = 4;
export const PHONE_NUMBERS_DO_NOT_MATCH = 45;
export const CLIENT_META_NOT_FOUND_EXCEPTION_CODE = 9;
export const CLIENT_META_EXISTS_EXCEPTION_CODE = 42;
export const CARD_NOT_MATCH_EXCEPTION_CODE = 43;
